manifest:
  remotes:
    - name: zmkfirmware
      url-base: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
  self:
    path: config
